import { supabase } from "@/lib/supabase-browser";
import { getClientCafeId } from "@/lib/cafe-context-client";
export interface OrderItemInput { menuItemId:string; quantity:number; price:number; }
export interface CreateOrderInput { tableId?:string|null; tableNumber?:number|null; customerName?:string|null; notes?:string|null; items:OrderItemInput[]; }
export async function createOrder(input:CreateOrderInput){if(!input.items.length)throw new Error("يجب إضافة منتج واحد على الأقل للطلب");if(!input.tableNumber)throw new Error("رقم الطاولة مطلوب");const cafeId=await getClientCafeId();const {data,error}=await supabase.rpc("create_order_with_items",{p_cafe_id:cafeId,p_table_number:input.tableNumber,p_client_request_id:crypto.randomUUID(),p_items:input.items.map(i=>({menu_id:Number(i.menuItemId),quantity:Number(i.quantity)}))});if(error)throw new Error(error.message);return data;}
export async function getOrders(){const cafeId=await getClientCafeId();const {data,error}=await supabase.from("orders").select(`*,order_items(*,menu(id,name_ar,price,image_url)),tables(table_number)`).eq("cafe_id",cafeId).order("created_at",{ascending:false});if(error)throw new Error(error.message);return data??[];}
export async function getOrder(id:string){const cafeId=await getClientCafeId();const {data,error}=await supabase.from("orders").select(`*,order_items(*,menu(id,name_ar,price,image_url)),tables(table_number)`).eq("id",id).eq("cafe_id",cafeId).single();if(error)throw new Error(error.message);return data;}
export async function updateOrderStatus(id:string,status:string){const cafeId=await getClientCafeId();const {data,error}=await supabase.from("orders").update({status}).eq("id",id).eq("cafe_id",cafeId).select().single();if(error)throw new Error(error.message);return data;}
export async function deleteOrder(id:string){const cafeId=await getClientCafeId();const {error}=await supabase.from("orders").delete().eq("id",id).eq("cafe_id",cafeId);if(error)throw new Error(error.message);}
