"use client";
import { useEffect, useState } from "react";

type Member={cafe_id:string;user_id:string;role:string;created_at:string;email:string|null};
const roles=["manager","cashier","kitchen","waiter","operator"];
export default function AdminStaffPage(){
 const [members,setMembers]=useState<Member[]>([]),[loading,setLoading]=useState(true),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[role,setRole]=useState("waiter"),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
 async function load(){setLoading(true);const r=await fetch('/api/admin/staff',{cache:'no-store'});const d=await r.json();if(r.ok)setMembers(d.members??[]);else setMessage(d.error||'غير مصرح');setLoading(false)}
 useEffect(()=>{load()},[]);
 async function add(e:React.FormEvent){e.preventDefault();setSaving(true);setMessage('');const r=await fetch('/api/admin/staff',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password,role})});const d=await r.json();if(!r.ok)setMessage(d.error||'تعذر إنشاء الموظف');else{setMessage('تم إنشاء الموظف وربطه بهذا المقهى.');setEmail('');setPassword('');await load()}setSaving(false)}
 async function remove(userId:string){if(!confirm('حذف الموظف من هذا المقهى؟'))return;const r=await fetch(`/api/admin/staff?userId=${encodeURIComponent(userId)}`,{method:'DELETE'});if(r.ok)load();else{const d=await r.json();setMessage(d.error||'تعذر الحذف')}}
 return <main className="min-h-screen bg-black p-6 text-white md:p-10"><div className="mx-auto max-w-6xl space-y-8" dir="rtl"><div><h1 className="text-4xl font-black text-yellow-400">موظفو المقهى</h1><p className="mt-2 text-zinc-400">كل موظف مرتبط بالمقهى المحدد فقط.</p></div><form onSubmit={add} className="grid gap-4 rounded-3xl border border-yellow-500/20 bg-zinc-950 p-6 md:grid-cols-3"><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="بريد الموظف" className="rounded-xl bg-zinc-900 p-3"/><input type="password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="كلمة المرور" className="rounded-xl bg-zinc-900 p-3"/><select value={role} onChange={e=>setRole(e.target.value)} className="rounded-xl bg-zinc-900 p-3">{roles.map(r=><option key={r} value={r}>{r}</option>)}</select><button disabled={saving} className="rounded-xl bg-yellow-500 py-3 font-black text-black md:col-span-3">{saving?'جارٍ الإنشاء...':'إضافة موظف'}</button>{message&&<p className="md:col-span-3 text-yellow-300">{message}</p>}</form><section className="rounded-3xl border border-white/10 bg-zinc-950 p-6"><h2 className="mb-5 text-2xl font-black">الموظفون الحاليون</h2>{loading?'جاري التحميل...':members.map(m=><div key={m.user_id} className="mb-3 flex items-center justify-between rounded-2xl bg-zinc-900 p-4"><div><p className="font-bold">{m.email||m.user_id}</p><p className="text-sm text-zinc-500">الدور: {m.role}</p></div>{m.role!=='owner'&&<button onClick={()=>remove(m.user_id)} className="rounded-xl border border-red-500/30 px-4 py-2 text-red-300">حذف</button>}</div>)}</section></div></main>
}
