"use client";

import { ChangeEvent, useMemo, useState } from "react";
import { ImagePlus, Plus, Save, Star, Trash2, Upload, X } from "lucide-react";
import { useMenu } from "@/hooks/useMenu";
import { useCategories } from "@/hooks/useCategories";
import { uploadMenuImage } from "@/services/storage";
import type { MenuItem } from "@/types/menu";

const EMPTY_FORM = { name: "", description: "", price: "", calories: "", image: "", category: "", available: true, featured: false, sort_order: 0 };
type FormState = typeof EMPTY_FORM;
const PLATFORM_CONTEXT = { platform: true } as const;
const FALLBACK_CATEGORIES: Record<number, string> = { 1: "القهوة الساخنة", 2: "القهوة الباردة", 3: "المشروبات", 4: "الحلويات", 5: "الوجبات الخفيفة", 6: "العروض الخاصة", 7: "المشروبات الصحية", 8: "الإضافات", 9: "المنتجات الجديدة", 10: "المشروبات المميزة", 11: "ركن القهوة" };
function categoryLabel(category: { name_ar?: string | null; sort_order?: number | null }) { const name = String(category.name_ar ?? "").trim(); return name && !/^\d+$/.test(name) ? name : (FALLBACK_CATEGORIES[Number(category.sort_order)] ?? "تصنيف بدون اسم"); }
async function publish(payload: Record<string, unknown>) { const response = await fetch("/api/admin/platform-settings/apply-menu", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json().catch(() => null); if (!response.ok || result?.ok !== true) throw new Error(result?.error || "تعذر حفظ تحديث المنيو."); return result; }

export default function PlatformMenuPanel() {
  const { items, loading, error, refresh } = useMenu(PLATFORM_CONTEXT); const { categories } = useCategories();
  const [search, setSearch] = useState(""); const [editorOpen, setEditorOpen] = useState(false); const [editing, setEditing] = useState<MenuItem | null>(null); const [form, setForm] = useState<FormState>(EMPTY_FORM); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [imagePreview, setImagePreview] = useState("");
  const filtered = useMemo(() => { const q = search.trim().toLowerCase(); return q ? items.filter(i => `${i.name} ${i.description}`.toLowerCase().includes(q)) : items; }, [items, search]);
  function getCategoryName(id: string) { const match = categories.find(c => String(c.id) === String(id)); return match ? categoryLabel(match) : "بدون تصنيف"; }
  function openCreate() { setEditing(null); setForm({ ...EMPTY_FORM, category: categories[0]?.id ? String(categories[0].id) : "" }); setImagePreview(""); setMessage(""); setEditorOpen(true); }
  function openEdit(item: MenuItem) { setEditing(item); setForm({ name: item.name, description: item.description, price: String(item.price), calories: item.calories == null ? "" : String(item.calories), image: item.image || "", category: item.category, available: item.available, featured: item.featured, sort_order: item.sort_order }); setImagePreview(item.image || ""); setMessage(""); setEditorOpen(true); }
  function closeEditor() { setEditorOpen(false); setEditing(null); setForm(EMPTY_FORM); setImagePreview(""); }
  function handleImageChange(e: ChangeEvent<HTMLInputElement>) { const file = e.target.files?.[0] ?? null; if (!file) return; setForm(f => ({ ...f, image: "" })); setImagePreview(URL.createObjectURL(file)); }
  async function handleSave() {
    if (!form.name.trim()) return setMessage("اسم المنتج مطلوب."); if (!form.category) return setMessage("اختر تصنيف المنتج."); if (!form.price || Number(form.price) < 0) return setMessage("أدخل سعرًا صحيحًا."); if (form.calories && (!Number.isFinite(Number(form.calories)) || Number(form.calories) < 0)) return setMessage("أدخل سعرات حرارية صحيحة.");
    setSaving(true); setMessage("");
    try { const file = document.querySelector<HTMLInputElement>("#platform-menu-image")?.files?.[0] ?? null; const imageUrl = file ? await uploadMenuImage(file) : form.image.trim(); const item = { name: form.name.trim(), description: form.description.trim(), price: Number(form.price), calories: form.calories.trim() === "" ? null : Number(form.calories), image: imageUrl, category: form.category, available: form.available, featured: form.featured, sort_order: Number(form.sort_order) || 0 }; await publish(editing ? { action: "update", id: editing.id, item } : { action: "create", item }); await refresh(); setMessage(editing ? "تم حفظ التعديل." : "تمت إضافة المنتج."); closeEditor(); } catch (err) { setMessage(err instanceof Error ? err.message : "تعذر حفظ المنتج."); } finally { setSaving(false); }
  }
  async function featured(item: MenuItem) { try { await publish({ action: "update", id: item.id, item: { name: item.name, description: item.description, price: item.price, calories: item.calories, image: item.image, category: item.category, available: item.available, featured: !item.featured, sort_order: item.sort_order } }); await refresh(); } catch (err) { setMessage(err instanceof Error ? err.message : "تعذر تغيير المميز."); } }
  async function available(item: MenuItem) { try { await publish({ action: "update", id: item.id, item: { name: item.name, description: item.description, price: item.price, calories: item.calories, image: item.image, category: item.category, available: !item.available, featured: item.featured, sort_order: item.sort_order } }); await refresh(); } catch (err) { setMessage(err instanceof Error ? err.message : "تعذر تغيير حالة المنتج."); } }
  async function remove(item: MenuItem) { if (!window.confirm(`حذف "${item.name}" من المقاهي؟`)) return; try { await publish({ action: "delete", id: item.id }); await refresh(); } catch (err) { setMessage(err instanceof Error ? err.message : "تعذر حذف المنتج."); } }

  return <div dir="rtl" className="rounded-3xl border border-white/10 bg-[#0b0d12] p-5 text-white sm:p-7">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><h3 className="text-2xl font-black text-yellow-400">إدارة المنيو والمنتجات</h3><p className="mt-1 text-sm text-zinc-500">كل خانة لها عنوان واضح، مع مثال داخل الخانة ورفع صورة من الكمبيوتر.</p></div><button type="button" onClick={openCreate} className="inline-flex items-center justify-center gap-2 rounded-xl bg-yellow-500 px-5 py-3 font-black text-black hover:bg-yellow-400"><Plus size={18}/> إضافة منتج</button></div>
    {message && <div className="mt-4 rounded-2xl border border-yellow-500/20 bg-yellow-500/10 px-4 py-3 text-sm font-bold text-yellow-300">{message}</div>}{error && <div className="mt-4 rounded-2xl border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm font-bold text-red-300">{error}</div>}
    {editorOpen && <div className="mt-6 rounded-3xl border border-yellow-500/20 bg-black/50 p-5 sm:p-6">
      <div className="mb-6 flex items-center justify-between"><div><h4 className="text-xl font-black">{editing ? "تعديل المنتج" : "إضافة منتج جديد"}</h4><p className="mt-1 text-sm text-zinc-500">العنوان فوق الحقل، والمثال داخل الحقل.</p></div><button type="button" onClick={closeEditor} className="rounded-xl border border-white/10 p-2 text-zinc-400 hover:text-white"><X size={18}/></button></div>
      <div className="grid gap-5 lg:grid-cols-2">
        <div><label className="mb-2 block text-sm font-bold text-white">اسم المنتج</label><input value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))} placeholder="مثال: كابتشينو" className="w-full rounded-xl border border-zinc-700 bg-zinc-900 px-4 py-3.5 text-white placeholder:text-zinc-600 outline-none focus:border-yellow-500"/></div>
        <div><label className="mb-2 block text-sm font-bold text-white">السعر</label><input type="number" min="0" step="0.01" value={form.price} onChange={e=>setForm(f=>({...f,price:e.target.value}))} placeholder="مثال: 18.00" className="w-full rounded-xl border border-zinc-700 bg-zinc-900 px-4 py-3.5 text-white placeholder:text-zinc-600 outline-none focus:border-yellow-500"/></div>
        <div><label className="mb-2 block text-sm font-bold text-white">السعرات الحرارية</label><input type="number" min="0" step="1" value={form.calories} onChange={e=>setForm(f=>({...f,calories:e.target.value}))} placeholder="مثال: 120 سعرة حرارية" className="w-full rounded-xl border border-zinc-700 bg-zinc-900 px-4 py-3.5 text-white placeholder:text-zinc-600 outline-none focus:border-yellow-500"/></div>
        <div><label className="mb-2 block text-sm font-bold text-white">تصنيف المنتج</label><select value={form.category} onChange={e=>setForm(f=>({...f,category:e.target.value}))} className="w-full rounded-xl border border-zinc-700 bg-zinc-900 px-4 py-3.5 text-white outline-none focus:border-yellow-500"><option value="">اختر تصنيف المنتج</option>{categories.map(c=><option key={c.id} value={String(c.id)}>{categoryLabel(c)}</option>)}</select></div>
        <div className="lg:col-span-2"><label className="mb-2 block text-sm font-bold text-white">صورة المنتج</label><div className="grid gap-4 md:grid-cols-[1fr_220px]"><div className="rounded-2xl border border-dashed border-zinc-700 p-4"><label htmlFor="platform-menu-image" className="flex min-h-36 cursor-pointer flex-col items-center justify-center rounded-xl border border-white/5 bg-black px-5 py-6 text-center hover:border-yellow-500/40"><ImagePlus size={30} className="mb-3 text-yellow-400"/><span className="font-black">اختيار صورة من الكمبيوتر</span><span className="mt-1 text-xs text-zinc-500">اضغط هنا ثم اختر الصورة من جهازك</span><input id="platform-menu-image" type="file" accept="image/png,image/jpeg,image/webp" onChange={handleImageChange} className="hidden"/></label><div className="mt-3 flex items-center gap-2 text-xs text-zinc-500"><Upload size={14}/>أو أدخل رابط الصورة يدويًا</div></div><div className="overflow-hidden rounded-2xl border border-zinc-700 bg-black">{imagePreview?<img src={imagePreview} alt="معاينة المنتج" className="h-full min-h-36 w-full object-cover"/>:<div className="flex min-h-36 items-center justify-center text-zinc-700"><ImagePlus size={34}/></div>}</div></div><input value={form.image} onChange={e=>{setForm(f=>({...f,image:e.target.value}));if(e.target.value)setImagePreview(e.target.value)}} placeholder="https://example.com/product.jpg" className="mt-3 w-full rounded-xl border border-zinc-700 bg-zinc-900 px-4 py-3 text-white placeholder:text-zinc-600 outline-none focus:border-yellow-500"/></div>
        <div className="rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><label className="flex items-center gap-3 text-sm font-bold"><input type="checkbox" checked={form.available} onChange={e=>setForm(f=>({...f,available:e.target.checked}))}/> المنتج متوفر</label></div>
        <div className="rounded-2xl border border-yellow-500/10 bg-zinc-950 p-4"><label className="flex items-center gap-3 text-sm font-bold"><input type="checkbox" checked={form.featured} onChange={e=>setForm(f=>({...f,featured:e.target.checked}))}/><Star size={17} className="text-yellow-400" fill={form.featured?"currentColor":"none"}/> منتج مميز</label></div>
      </div>
      <div className="mt-6 flex gap-3"><button type="button" disabled={saving} onClick={()=>void handleSave()} className="inline-flex items-center gap-2 rounded-xl bg-yellow-500 px-6 py-3 font-black text-black hover:bg-yellow-400 disabled:opacity-60"><Save size={18}/>{saving?"جارٍ الحفظ...":editing?"حفظ التعديل":"إضافة المنتج"}</button><button type="button" onClick={closeEditor} className="rounded-xl border border-white/10 px-6 py-3 font-bold text-zinc-300">إلغاء</button></div>
    </div>}
    <div className="mt-6"><label className="mb-2 block text-sm font-bold text-white">البحث في المنتجات</label><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="مثال: كابتشينو" className="w-full rounded-xl border border-white/10 bg-black px-4 py-3 text-white placeholder:text-zinc-600 outline-none focus:border-yellow-500"/></div>
    <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{loading?<div className="md:col-span-2 xl:col-span-3 rounded-2xl border border-white/10 p-10 text-center text-zinc-500">جاري تحميل المنيو...</div>:filtered.length===0?<div className="md:col-span-2 xl:col-span-3 rounded-2xl border border-dashed border-white/10 p-10 text-center text-zinc-500">لا توجد منتجات.</div>:filtered.map(item=><article key={item.id} className="overflow-hidden rounded-2xl border border-white/10 bg-zinc-950"><div className="relative">{item.image?<img src={item.image} alt={item.name} className="h-44 w-full object-cover"/>:<div className="flex h-44 items-center justify-center bg-zinc-900 text-4xl">☕</div>}<button type="button" onClick={()=>void featured(item)} title={item.featured?"إزالة من المميز":"إضافة للمميز"} className={`absolute left-3 top-3 flex h-11 w-11 items-center justify-center rounded-full border ${item.featured?"border-yellow-400 bg-yellow-400 text-black":"border-white/20 bg-black/70 text-white hover:border-yellow-400 hover:text-yellow-400"}`}><Star size={21} fill={item.featured?"currentColor":"none"}/></button></div><div className="p-4"><div className="flex items-start justify-between gap-3"><div><h4 className="text-lg font-black">{item.name}</h4><p className="mt-1 text-xs font-bold text-yellow-400">{getCategoryName(item.category)}</p></div><span className="text-lg font-black text-yellow-400">{item.price} ر.س</span></div><p className="mt-3 min-h-12 text-sm leading-6 text-zinc-500">{item.description||"لا يوجد وصف للمنتج."}</p>{item.calories!=null&&<p className="mt-2 text-xs font-bold text-zinc-400">{item.calories} سعرة حرارية</p>}<div className="mt-4 grid grid-cols-2 gap-2"><button type="button" onClick={()=>void available(item)} className="rounded-xl border border-orange-500/20 bg-orange-500/10 px-3 py-2.5 text-sm font-bold text-orange-400">{item.available?"إخفاء المنتج":"إظهار المنتج"}</button><button type="button" onClick={()=>openEdit(item)} className="rounded-xl border border-blue-500/20 bg-blue-500/10 px-3 py-2.5 text-sm font-bold text-blue-400">تعديل</button><button type="button" onClick={()=>void remove(item)} className="col-span-2 inline-flex items-center justify-center gap-2 rounded-xl border border-red-500/20 bg-red-500/10 px-3 py-2.5 text-sm font-bold text-red-400"><Trash2 size={16}/> حذف المنتج</button></div></div></article>)}</div>
  </div>;
}
