"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
type Cafe={id:string;name:string;slug:string;owner_user_id:string|null;is_active:boolean;created_at:string};
export default function AdminCafesPage(){
 const [cafes,setCafes]=useState<Cafe[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[name,setName]=useState(""),[slug,setSlug]=useState(""),[ownerEmail,setOwnerEmail]=useState(""),[ownerPassword,setOwnerPassword]=useState("");
 async function load(){setLoading(true);const r=await fetch("/api/admin/cafes",{cache:"no-store"});const d=await r.json();if(r.ok)setCafes(d.cafes??[]);else setMessage(d.error||"تعذر تحميل المقاهي.");setLoading(false)}
 useEffect(()=>{load()},[]);
 async function createCafe(e:React.FormEvent){e.preventDefault();setSaving(true);setMessage("");const r=await fetch("/api/admin/cafes",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,slug,ownerEmail,ownerPassword})});const d=await r.json();if(!r.ok){setMessage(d.error||"تعذر إنشاء المقهى.");setSaving(false);return}setMessage("تم إنشاء المقهى وحساب المالك بنجاح.");setName("");setSlug("");setOwnerEmail("");setOwnerPassword("");await load();setSaving(false)}
 async function activate(id:string){const r=await fetch("/api/admin/cafes/active",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({cafeId:id})});if(r.ok){try{window.localStorage.setItem("active_cafe_context",id);}catch{} window.location.assign(`/admin?cafe=${encodeURIComponent(id)}`);}else setMessage("تعذر اختيار المقهى.")}
 return <main className="min-h-screen bg-black p-6 text-white md:p-10"><div className="mx-auto max-w-7xl space-y-8" dir="rtl"><div className="flex items-end justify-between gap-4"><div><h1 className="text-4xl font-black text-yellow-400">إدارة المقاهي</h1><p className="mt-2 text-zinc-400">إنشاء وإدارة المقاهي المستقلة داخل المنصة.</p></div><Link href="/admin/settings" className="rounded-xl border border-zinc-700 px-4 py-3 hover:border-yellow-500">الإعدادات</Link></div><form onSubmit={createCafe} className="grid gap-4 rounded-3xl border border-yellow-500/20 bg-zinc-950 p-6 md:grid-cols-2"><input value={name} onChange={e=>setName(e.target.value)} placeholder="اسم المقهى" required className="rounded-xl bg-zinc-900 p-3 outline-none"/><input value={slug} onChange={e=>setSlug(e.target.value)} placeholder="الرابط: cafe-name" required className="rounded-xl bg-zinc-900 p-3 outline-none"/><input type="email" value={ownerEmail} onChange={e=>setOwnerEmail(e.target.value)} placeholder="بريد مالك المقهى" required className="rounded-xl bg-zinc-900 p-3 outline-none"/><input type="password" value={ownerPassword} onChange={e=>setOwnerPassword(e.target.value)} placeholder="كلمة مرور المالك (8+ أحرف)" minLength={8} required className="rounded-xl bg-zinc-900 p-3 outline-none"/><button disabled={saving} className="rounded-xl bg-yellow-500 px-6 py-3 font-black text-black md:col-span-2 disabled:opacity-50">{saving?"جارٍ الإنشاء...":"إنشاء مقهى جديد"}</button>{message&&<p className="md:col-span-2 text-sm text-yellow-300">{message}</p>}</form><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{loading?<div>جاري تحميل المقاهي...</div>:cafes.map(c=><article key={c.id} className="rounded-3xl border border-white/10 bg-zinc-950 p-6"><div className="flex items-start justify-between gap-3"><div><h2 className="text-2xl font-black">{c.name}</h2><p className="mt-1 text-sm text-zinc-500">/{c.slug}</p></div><span className={c.is_active?"text-emerald-400":"text-red-400"}>{c.is_active?"نشط":"متوقف"}</span></div><button onClick={()=>activate(c.id)} className="mt-6 w-full rounded-xl border border-yellow-500/30 py-3 font-bold text-yellow-300 hover:bg-yellow-500 hover:text-black">فتح لوحة هذا المقهى</button><a href={`/?cafe=${encodeURIComponent(c.slug)}`} target="_blank" rel="noreferrer" className="mt-3 block w-full rounded-xl border border-white/10 py-3 text-center font-bold text-zinc-300 hover:border-yellow-500/30 hover:text-yellow-300">معاينة موقع هذا المقهى</a></article>)}</section></div></main>
}
